base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name ="index"),
    path('post/<slug:slug>/', views.post, name ="post"),
    path('posts/', views.posts, name ="posts"),
    path('about/', views.about, name ="about"),
    path('resume/', views.resume, name ="resume"),
    path('portfolio/', views.portfolio, name ="portfolio"),
    path('contact/', views.contact, name ="contact"),

    #CRUD 
    
    path('create_post/', views.createPost, name="create_post"),
    path('update_post/<slug:slug>/', views.updatePost, name="update_post"),
    path('delete_post/<slug:slug>/', views.deletePost, name="delete_post"),

    path('send_email/', views.sendEmail, name="send_email"),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Post(models.Model):
    headline = models.CharField(max_length=200)
    sub_headline = models.CharField(max_length=200, null=True, blank=True)
    thumbnail = models.ImageField(null=True, blank=True, upload_to="img", default="sample.jpg")
    body = RichTextUploadingField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, null=True)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.headline

    def save(self, *args, **kwargs):

        if self.slug == None:
            slug = slugify(self.headline)

            has_slug = Post.objects.filter(slug=slug).exists()
            count = 1
            while has_slug:
                count += 1
                slug = slugify(self.headline) + '-' + str(count)
                has_slug = Post.objects.filter(slug=slug).exists()


            self.slug = slug
        
        super().save(*args, **kwargs)

base/forms.py
from django import forms
from django.forms import ModelForm

from .models import Post

class PostForm(ModelForm):

    class Meta:
        model = Post
        fields = '__all__'


        widgets = {
            'tags':forms.CheckboxSelectMultiple(),
        }

base/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.
from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string

from .forms import PostForm
from .filters import PostFilter

from .models import Post

def home(request):
    posts = Post.objects.filter (active=True, featured=True)[0:3]

    context = {'posts':posts}
    return render(request, 'base/index.html', context)

def about(request):
    return render(request, 'base/about.html')

def resume(request):
    return render(request, 'base/resume.html')

def posts(request):
    posts = Post.objects.filter(active=True)
    myFilter = PostFilter(request.GET, queryset=posts)
    posts = myFilter.qs
    
    page = request.GET.get('page')

    paginator = Paginator(posts, 3)

    try:
        posts = paginator.page(page)
    except PageNotAnInteger :
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {'posts':posts, 'myFilter':myFilter}
    return render(request, 'base/posts.html' , context)

def post(request, slug):
    post = Post.objects.get(slug=slug)

    context = {'post':post}
    return render(request, 'base/post.html', context)

def portfolio(request): 
    return render(request, 'base/portfolio.html')

def contact(request):
    return render(request, 'base/contact.html')

#CRUD

@login_required(login_url="home")
def createPost(request):
    form = PostForm()
    
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('posts')
    context = {'form':form}
    return render(request, 'base/post_form.html', context)

@login_required(login_url="home")
def updatePost(request, slug):
    post = Post.objects.get(slug=slug)
    form = PostForm(instance=post)
    
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
        return redirect('posts')
    context = {'form':form}
    return render(request, 'base/post_form.html', context)

@login_required(login_url="home")
def deletePost(request, slug):
    post = Post.objects.get(slug=slug)
    
    if request.method == "POST":
        post.delete()
        return redirect('posts')
    context = {'item':post}
    return render(request, 'base/delete.html', context)

def sendEmail(request):

    if request.method == 'POST':

        template = render_to_string('base/email_template.html', {
            'Firstname':request.POST['Firstname'],
            'Lastname':request.POST['Lastname'],
            'email':request.POST['email'],
            'message':request.POST['message'],
            })

        email = EmailMessage (
            request.POST['subject'],
            template,
            settings.EMAIL_HOST_USER,
            ['tazsafakhri@gmail.com']
            )

        email.fail_silently = False
        email.send()

    return render(request, 'base/email_sent.html')

base/templates/base/contact.html
{% extends 'base/main.html'%}

{% block content %}


&nbsp;
&nbsp;
<div class="container mt-5">

 
    <!--Section: Content-->
    <section class="dark-grey-text mb-5">
      
      <style>
        .map-container-section {
          overflow:hidden;
          padding-bottom:56.25%;
          position:relative;
          height:0;
        }
        .map-container-section iframe {
          left:0;
          top:0;
          height:100%;
          width:100%;
          position:absolute;
        }
      </style>

      <!-- Section heading -->
      <div class="section-title" style="text-align: center;" >
        <!-- Main heading -->
        <h1 style="font-family: 'Dancing Script', cursive; font-size: 18px;">I will Reply in Timely Manner and thank you for </h1>
        <p style="font-size: 72px; margin-top: -30px; font-family: 'Luckiest Guy', cursive;"> Contact Me! </p>
        <!-- Main heading -->

      </div>
      <!-- Section description -->


      <!-- Grid row -->
      <div class="row">

        <!-- Grid column -->
        <div class="col-lg-5 mb-lg-0 pb-lg-3 mb-4">

          <!-- Form with header -->
          <div class="card">
            <div class="card-body">
              <!-- Header -->
              <div class="form-header blue accent-1">
                <h3 class="mt-2"><i class="fas fa-envelope"></i> Write to me:</h3>
              </div>
              <p class="dark-grey-text">i'll contact back in timely manner.</p>
              <!-- Body -->
              <form id="contact-form" method="POST" action= "{% url 'send_email' %}">
                {% csrf_token %}
                <div class="md-form"  >
                  <i class="fas fa-user prefix grey-text"></i>
                  <input name="Firstname" type="text" id="form-name" class="form-control">
                  <label for="Firstname">First Name</label>
                </div>
                <div class="md-form"  >
                <i class="fas fa-user prefix grey-text"></i>
                <input name="Lastname" type="text" id="form-name" class="form-control">
                <label for="Lastname">Last Name</label>
              </div>
                <div class="md-form">
                  <i class="fas fa-envelope prefix grey-text"></i>
                  <input name="email" type="text" id="form-email" class="form-control">
                  <label for="email">Your email</label>
                </div>
                <div class="md-form">
                  <i class="fas fa-tag prefix grey-text"></i>
                  <input name="subject" type="text" id="form-Subject" class="form-control">
                  <label for="subject">Subject</label>
                </div>
                <div class="md-form">
                  <i class="fas fa-pencil-alt prefix grey-text"></i>
                  <textarea id="form-text" class="form-control md-textarea" rows="3" name="message"></textarea>
                  <label for="message">Send message</label>
                </div>
                <div class="text-center">
                  <button type="submit" class="btn btn-light-blue">Submit</button>
                </div>
              </form>
              
            </div>
          </div>
          <!-- Form with header -->

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-lg-7">
          <div id="map-container-section" class="z-depth-1-half map-container-section mb-4" style="height: 400px">
            <iframe src="https://www.google.com/maps/embed?pb=!1m27!1m12!1m3!1d3958.698083027201!2d108.00584571513005!3d-7.160860494829581!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m12!3e0!4m5!1s0x2e68b37d93172f01%3A0x0!2s-7.160885696791679%2C%20108.00811530253826!3m2!1d-7.1608382!2d108.00803379999999!4m4!2s-7.160885696791679%2C%20108.00811530253826!3m2!1d-7.1608857!2d108.0081153!5e0!3m2!1sid!2sid!4v1608268809641!5m2!1sid!2sid" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
          </div>
          <div class="row text-center">
            <div class="col-md-4">
                <i class="fas fa-map-marker-alt px-4 green-text"></i>
              </a>
              <p>Garut, 44184</p>
              <p class="mb-md-0">Indonesia</p>
            </div>
            <div class="col-md-4">
                <i class="fas fa-phone px-4 green-text"></i>
              </a>
              <p>+62 81 8086 2017</p>
              <p class="mb-md-0">Mon - Fri, 8:00-22:00</p>
            </div>
            <div class="col-md-4">
                <i class="far fa-envelope px-4 green-text"></i>
              </a>
              <p>tazsafakhri@gmail.com</p>
            </div>
          </div>
        </div>
      </div>
    </section>
</div> 

{% endblock content %}

base/templates/base/delete.html
{% extends 'base/main.html' %}
{% load static %}

{% block content %}
&nbsp;
&nbsp;
<div class="section-title" style="text-align: center; margin-top: 60px;" >
    <form action= "" method="POST">
        {% csrf_token%}
        <p> Are you sure want to delete {{item}} ?</p>
        <input class="btn btn-danger" type="submit" value="Confirm">
        </form>
</div>

{% endblock content %}

base/templates/base/email_sent.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}
&nbsp;
&nbsp;


<div id="success-box" class="section-title" style="text-align: center; margin-top: 60px;" >
    <img class="resize" src="{% static 'img/tenor.gif' %}">
    <br>
    <h1 style="font-family: 'Dancing Script', cursive; font-size: 24px; margin-top: 40px;"">Thanks For Reaching out!</h1>
    <p style="font-size: 36px; margin-top: -10px; font-family: 'Luckiest Guy', cursive; color: #fff;"> Your Message was successfully sent. I will do my best to get back to you in timely manner </p>
    <a id ="back-btn" href="{% url 'index' %}">BACK TO HOMEPAGE</a>

</div>
{% endblock %}

base/templates/base/email_template.html
{{Firstname}} {{Lastname}}

{{subject}}

{{message}}



{{email}}

base/templates/base/index.html
{% extends 'base/main.html'%}

{% load static %}
{% include 'base/navbar.html' %}
{% block content %}

    <!--Carousel Wrapper-->
    <div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel">

        <!--Indicators-->
        <ol class="carousel-indicators">
        <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-1z" data-slide-to="1"></li>
        <li data-target="#carousel-example-1z" data-slide-to="2"></li>
        </ol>
        <!--/.Indicators-->
    
        <!--Slides-->
        <div class="carousel-inner" role="listbox">
    
        <!--First slide-->
        <div class="carousel-item active">
            <div class="view" style="background-image: url({% static 'img/bg.jpg' %}); background-repeat: no-repeat; background-size: cover;">
    
            <!-- Mask & flexbox options-->
            <div class="mask rgba-black-light d-flex justify-content-center align-items-center">
    
                <!-- Content -->
                <div class="text-center white-text mx-5 wow fadeIn">
                <h1 class="mb-4" style="font-family: 'Permanent Marker', cursive; font-size: 60px;">
                    <strong>Hi!, Im Tasa Fachri Oktasar</strong>
                </h1>
    
                <p>
                    <strong style="font-family: 'Lobster', cursive; font-size: 24px;">Generalist Human Resources</strong>
                </p>
    
                </div>
                <!-- Content -->
    
            </div>
            <!-- Mask & flexbox options-->
    
            </div>
        </div>
        <div class="carousel-item">
            <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Others/images/94.jpg'); background-repeat: no-repeat; background-size: cover;">
    
            <!-- Mask & flexbox options-->
            <div class="mask rgba-black-light d-flex justify-content-center align-items-center">
    
                <!-- Content -->
                <div class="text-center white-text mx-5 wow fadeIn">
                <p class="mb-4 d-none d-md-block" style="font-family: 'Lobster', cursive; font-size: 40px;">
                    <strong>And, welcome to my homepage, 
                        <br>so I have to say something about myself. 
                        <br>Sometimes it is hard to introduce yourself because you know yourself,
                        <br>so well that you do not know where to start with.
                        <br>Let me give a try to see what kind of image you have about me through my self-description. 
                        <br>I hope that my impression about myself and your impression about me are not so different. Here it goes.</strong>
                </p>
                </div>
            </div>
            </div>
        </div>
    
        <div class="carousel-item">
            <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Others/images/92.jpg'); background-repeat: no-repeat; background-size: cover;">
            <div class="mask rgba-black-light d-flex justify-content-center align-items-center">
                <div class="text-center white-text mx-5 wow fadeIn">
                <p class="mb-4 d-none d-md-block" style="font-family: 'Lobster', cursive;font-size: 40px;">
                    <strong>Hope u like it! </strong>
                </p>
                </div>
            </div>
            </div>
        </div>
        </div>
        <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
        </a>
    </div>

    <main>
        <div class="container">
    
       <!--Section: Main info-->
    
        <hr class="my-5">
    
        <!--Section: Main features & Quick Start-->
        <section>
            
            <h3 class="h3 text-center mb-5">What I'm currently doing ?</h3>
    
            <!--Grid row-->
            <div class="row wow fadeIn">
    
            <!--Grid column-->
            <div class="col-lg-6 col-md-12 px-4">
    
                <!--First row-->
                <div class="row">
                <div class="col-1 mr-3">
                    <i class="fas fa-check-double fa-2x cyan-text" aria-hidden="true"></i>
                </div>
                <div class="col-10">
                    <h5 class="feature-title">Passionate about </h5>
                    <p class="grey-text" style="text-align: justify;">In terms of the work, im working past eight years as Human Resources Staff, IT Staff also Project Staff, but i found interest as developer, and right now im focusing on Python, Django + React</p>
                    <br>
                    <p style="color: rgb(138, 136, 136); text-align: justify;">The world is changing rapidly, and I don’t have enough professional experience as Python / Django Programming Language nor Data Scientis. However, I know that I can provide a fresh take and an extraordinary approach to every project</p>
                    <a href="#">more about my resume</a>
                </div>
                </div>
                <!--/First row-->
    
                <div style="height:30px"></div>
    

    
                <div style="height:30px"></div>
 
            </div>
            <!--/Grid column-->
    
            <!--Grid column-->
            <div class="col-lg-6 col-md-12">
    
                <p class="h5 text-center mb-4">My Youtube Channel</p>
                <div id="ytplayer" class="embed-responsive embed-responsive-16by9">
                <iframe  class="embed-responsive-item" src="https://www.youtube.com/channel/UCAB-ZfiZIZ-z0bqXAYQ2Fbw" frambeborder=0 allowfullscreen></iframe>
                </div>
            </div>
            <!--/Grid column-->
    
            </div>
            <!--/Grid row-->
    
        </section>
        <!--Section: Main features & Quick Start-->

        <hr class="mb5">
        <div class="container mt-5">


            <!--Section: Content-->
            <section class="text-center">
            
              <!-- Section heading -->
              <h3 class="font-weight-bold mb-5">Featured Blog Posts</h3>
                
                <!-- Grid row -->
              <div class="row">

                {% for post in posts %}  
                <!-- Grid column -->
                <div class="col-lg-4 col-md-12 mb-lg-0 mb-4">
                  
                  <!-- Card -->
                  <div class="card hoverable">
                    
                    <!-- Card image -->
                    <img class="card-img-top" src="{{post.thumbnail.url}}">
          
                    <!-- Card content -->
                    <div class="card-body">
          
                      <!-- Title -->
                      <p class="card-title text-muted text-uppercase font-small mt-1 mb-3"><strong>{{post.headline}}</strong></p>
                      <!-- Text -->
                      <p class="mb-2" style="text-align: justify;">{{post.sub_headline}}</p>
                      <hr>
                      <a href="{% url 'post' post.slug %}">Read More</a>
          
                    </div>

          
                  </div>
                  
                  <!-- Card -->

                  
                </div>
                {% endfor %}  
 
                
              </div>
              <!-- Grid row -->
              <br>
              <p><a href="{% url 'posts' %}">View More</a></p>
      
            </section>
            <!--Section: Content-->
          
          
        </div>
        
    
        <hr class="mb-5">
    
    <section class="px-md-5 mx-md-5 text-center text-lg-left dark-grey-text">

        <form id="contact-form" method="POST" action="{% url 'send_email' %}"> 
            <div class="row">
                <div class="col-lg-5 col-md-12 mb-0 mb-md-0">
                  <h3 class="font-weight-bold">Need More Info ?</h3>
                  <p class="text-muted" style="text-align: justify;">With any other inquiries into the matter at hand, I offer you my utmost sincerity to provide service should you require further assistance at any later point in time which is not necessarily right at this moment during the immediate conversation that we are engaging in currently.</p>
                  <p><span class="font-weight-bold mr-2">Email:</span><a href="">tazsafakhri@gmail.com</a></p>
                  <p><span class="font-weight-bold mr-2">Phone:</span><a href="">+62 81 8086 2017</a></p>
                </div>
                {% csrf_token%}
                <div class="col-lg-7 col-md-12 mb-4 mb-md-0">
                  <div class="row">
                    <div class="col-md-6">
                      <div class="md-form md-outline mb-0">
                        <input type="text" id="form-first-name" class="form-control" name="Firstname">
                        <label for="form-first-name" >First name</label>
                      </div>
        
                    </div>
                    <div class="col-md-6">
                      <div class="md-form md-outline mb-0">
                        <input type="text" id="form-last-name" class="form-control" name="Lastname">
                        <label for="form-last-name">Last name</label>
                      </div>
        
                    </div>
                  </div>
                  <div class="md-form md-outline mt-3">
                    <input type="email" id="form-email" class="form-control" name="email">
                    <label for="form-email">E-mail</label>
                  </div>
                  <div class="md-form md-outline">
                    <input type="text" id="form-subject" class="form-control" name="subject">
                    <label for="form-subject">Subject</label>
                  </div>
                  <div class="md-form md-outline mb-3">
                    <textarea id="form-message" class="md-textarea form-control" rows="3" name="message"></textarea>
                    <label for="form-message">How i can help?</label>
                  </div>
                  <button type="submit" class="btn btn-info btn-sm ml-0">Submit<i class="far fa-paper-plane ml-2"></i></button>
                </div>
              </div>
        </form>
        
  
    </section>
    
        </div>
    </main>
    <!--Main layout-->
    
    
        <script>
            // Load the IFrame Player API code asynchronously.
            var tag = document.createElement('script');
            tag.src = "https://www.youtube.com/player_api";
            var firstScriptTag = document.getElementsByTagName('script')[0];
            firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
          
            // Replace the 'ytplayer' element with an <iframe> and
            // YouTube player after the API code downloads.
            var player;
            function onYouTubePlayerAPIReady() {
              player = new YT.Player('ytplayer', {
                height: '360',
                width: '640',
                videoId: 'IzabzadpROQ'
              });0
            }
        </script>

    
    </footer>
    <!--/.Footer-->
    {% endblock content %}

base/templates/base/post_form.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
&nbsp;
&nbsp;

<style type="text/css">
    #div_id_tags > div {
        max-height: 10px;
        overflow-y: scroll;
        border: 1px solid #888;
        padding: 5px;
        border-radius: 5px;
    }

</style>
<div class="container"  style="color: #fff;">
        <div class="section-title" style="text-align: center; margin-top: 60px; color: #fff;" >
            <!-- Main heading -->
            <p style="font-size: 72px; margin-top: -30px; font-family: 'Luckiest Guy', cursive; color: #fff; "> Post Form </p>
            <!-- Main heading -->
        </div>
        <form action= "" method="POST" enctype="multipart/form-data" style="color: #fff;">
        {% csrf_token%}
        {{form.media}}
        {{form|crispy}}
        <input class="btn btn-success" type="submit" value="Submit Post" >
        </form>
</div>
{% endblock %}

base/templates/base/posts.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'base/navbar.html' %}
&nbsp;
&nbsp;
<style type="text/css">
    #id_tags{
        overflow-y: scroll;
        max-height: 100px;
        border-radius: 5px;
        padding: 5px;
    }
    .news-tile .card-title {
        position: absolute;
        bottom: 15px;
        left: 40px;
      }

      .rgba-stylish-strong {
        background-color: rgba(62, 69, 81, .5);
      }
</style>

<div class="section-title" style="text-align: center; margin-top: 60px;" >
    <p style="color: #fff; font-size: 72px; margin-top: -30px; font-family: 'Luckiest Guy', cursive;"> Posts </p>


    
</div>




<div class="container" style="margin-top: 10px;">   
    {% if request.user.is_authenticated %}
    <a class="nav-link" href="{% url 'create_post' %}" style="text-align: center; margin-top: -40px;">Create Post</a>  
    {% endif %} 
    <div>
        <form id="searchForm" method="GET" class="" style="color: #fff;">
            {{myFilter.form|crispy}}
            <input class="btn btn-primary" type="submit" value="Search" >
        </form>

    </div>

    <div class="row">
        {% for post in posts %}
        <!-- Grid column -->
        <div class="col-lg-4 col-md-12 mb-lg-0 mb-4" style="margin-top: 20px;">
  
          <!-- Card -->
            <div class="card hoverable">
  
                <!-- Card image -->
                <img class="card-img-top" src="{{post.thumbnail.url}}" alt="Card image cap">
    
                <!-- Card content -->
                <div class="card-body">
                
                <!-- Title -->
                <p class="card-title text-muted text-uppercase font-small mt-1 mb-4">{{post.headline}}</p>
                <!-- Text -->
                <p class="mb-2" style="text-align: justify;">{{post.sub_headline}}</p>
                {% if request.user.is_authenticated %}
                <a href="{% url 'post' post.id%}" style="font-size: 10px; padding: 10px;" class="btn aqua-gradient">Read More</a>
                <a href="{% url 'update_post' post.slug %}" style="font-size: 10px; padding: 10px 25px;" class="btn aqua-gradient">Edit</a>
                <a href="{% url 'delete_post' post.slug %}" style="font-size: 10px; padding: 10px 17px;" class="btn aqua-gradient">Delete</a>
                {% endif%} 
                <hr>
                {% for tag in post.tags.all %}
                    <span class="tag">{{tag}}</span>
                {% endfor %}
                <hr> 
            </div>
        </div>
      </div>
        {% empty %}
        <h3>No Post Found ..</h3>
        {% endfor %}    
      <!-- Grid row -->
    </div>  


    <div>
        <nav aria-label="Page navigation example" >
            {% if posts.has_other_pages%}
                <ul class="pagination" style="justify-content: center;">
                {% if posts.has_previous%}  
                <li class="page-item"><a data-page="{{posts.previous_page_number}}" href="?page={{posts.previous_page_number}}" class="page-link"> &laquo</a></li>
        
                <li class="page-item"><a data-page="1" href="?page=1" class="page-link"> First</a></li>
                {% endif %}
        
                {% for i in posts.paginator.page_range %}
                    {% if posts.number == i %}
                        <li class="page-item"><a class="active page-link">{{i}}</a></li>
                    {% else %}
                        <li class="page-item"><a data-page="{{i}}" href="?page={{i}}" class="page-link">{{i}}</a></li>
                    {% endif %}
                {% endfor%}
        
                {% if posts.has_next %}
                        <li class="page-item"><a data-page="{{posts.paginator.num_pages}}" href="?page={{posts.paginator.num_pages}}" class="page-link">{{i}}</a></li>
        
                        <li class="page-item"><a data-page="{{posts.next_page_number}}" href="?page={{posts.next_page_number}}" class="page-link">&raquo</a></li>
                {% endif %}
                </ul>
            {% endif %}
        </nav>   
    </div>
</div>
<footer class="page-footer text-center font-small mdb-color darken-2 mt-4 wow fadeIn">

    
    <hr class="my-4">
    <div class="pb-4">
        <a href="https://www.facebook.com/mdbootstrap" target="_blank">
            <i class="fab fa-facebook-f mr-3"></i>
        </a>

        <a href="https://twitter.com/MDBootstrap" target="_blank">
            <i class="fab fa-twitter mr-3"></i>
        </a>

        <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
            <i class="fab fa-youtube mr-3"></i>
        </a>

        <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
            <i class="fab fa-google-plus-g mr-3"></i>
        </a>

        <a href="https://dribbble.com/mdbootstrap" target="_blank">
            <i class="fab fa-dribbble mr-3"></i>
        </a>

        <a href="https://pinterest.com/mdbootstrap" target="_blank">
            <i class="fab fa-pinterest mr-3"></i>
        </a>

        <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
            <i class="fab fa-github mr-3"></i>
        </a>

        <a href="http://codepen.io/mdbootstrap/" target="_blank">
            <i class="fab fa-codepen mr-3"></i>
        </a>
    </div>
</footer>

<script type="text/javascript">
    let searchForm = document.getElementById('searchForm')
    let pageLinks = document.getElementsByClassName('page-link')

    for(var i=0; pageLinks.length; i++){

        pageLinks[i].addEventListener('click', function(e){
            e.preventDefault()
            let page = this.dataset.page
            console.log('Page', page)
            searchForm.innerHTML += '<input value="${page}" name="page" hideen >'
            searchForm.submit()
        })

    }
</script>

{% endblock content%}